### ISSUE TITLE
$primary no longer being read from w-tree.vue, typeof item does not check for null value

### ISSUE THREAD

**Issue by tomit4** [antoniandre/wave-ui#120]
Issues with $primary in src/components/ w-tree.vue line 315:
```
        &:focus:before {
            background-color: rgba($primary,  0.1);
        }
```
Vite complains that $primary is not defined. Hacked workaround to:
```
        &:focus:before {
            background-color: rgba(#234781, 0.1);
        }
```
Also, issue with createSelection() method in src/components/w-select.vue line 353:
```
                    if (typeof item === 'object') {
```
Doesn't check if item is null since typeof item === 'object' will be true if item is null, please change to:
```
                    if (typeof item === 'object' && item !== null) {
```

**Comment by antoniandre** [comment]
Hi @tomit4 thanks for your feedback.
I actually noticed and fixed the w-select already.
For the $primary variable, it should be available since it is defined in /src/wave-ui/scss/_variables.scss.
Let me know if you're still facing the issue, and if so please reopen the issue with a reproduction link. You can fork from this one: https://stackblitz.com/edit/waveui-3
Cheers!
