### ISSUE TITLE
about w-dialog

### ISSUE THREAD

**Issue by HenryLin0914** [antoniandre/wave-ui#14]
Hi !!!

we very like your w-dialog 

we hope can call api to use it 

ex.   
```
this.$wave.dialog({
               type: 'confirm',
               title: 'title',
               text: 'text',
               .....
       })
```

**Comment by antoniandre** [comment]
Thanks for your feedback @HenryLin0914, I'll think about it and will let you know.

**Comment by antoniandre** [comment]
Hi @HenryLin0914 Thanks again for your suggestion.
It will actually not be possible, for a few reasons:
- I am planning to support tree-shaking and this would be problematic 
- If I do this for the dialog component why not the other ones (tooltip, drawer, etc) that would then double the work
- Supporting this function call would also mean supporting a bunch of options to style, and parameter as wished
- all this would require a lot of extra code, and a little bit unnecessary since you can create this behavior in your code. 

For these reasons I will not add this feature. I hope it makes sense to you and I appreciate your support and ideas!
Let me know if you have other questions or suggestions on other topics. 😉
