### ISSUE TITLE
Nicer integration of tables and cards

### ISSUE THREAD

**Issue by djmattyg007** [antoniandre/wave-ui#35]
If there is a table inside the body of a card, it would be nice if the two worked together a bit:

1. Remove the padding from the card body
2. Remove the border from the table

**Comment by antoniandre** [comment]
Hi @djmattyg007,

I've added more CSS helper classes to help on that matter :)
https://antoniandre.github.io/wave-ui/shadows-borders-radii

Here is an example for your case: https://codepen.io/antoniandre/pen/mdOzdzb?editors=101

Hope it helps.

**Comment by djmattyg007** [comment]
It would be nice though if it could automatically apply this when it detects a table inside the card, similar to how the appearance of toolbars change their appearance when they're inside a card's header.

**Comment by antoniandre** [comment]
@djmattyg007, I understand your point and thanks for your suggestion!
But for this case it would not make more sense to default to no padding on the `w-card` when there is a `w-table` inside, since the user may intend to have a padding, and a border on table, for instance if the table is white and the w-card has a green background. 
In addition, the w-card default is to have a padding, and removing it by default only in some nesting cases adds complexity in the understanding of the component. 
The `w-toolbar` case in `w-card` title or action is special and well "framed" as this is the only possible behavior to occupy the full width of the card.

So the best we can do here is offering parameters to control what you exactly want, like in the Codepen.
I hope it makes sense :)

**Comment by djmattyg007** [comment]
Thank you for your consideration, I appreciate it and respect your decision :)

**Comment by antoniandre** [comment]
Awesome, closing the issue then. 👌
