### ISSUE TITLE
w-icon uses inline style, breaks strict CSP

### ISSUE THREAD

**Issue by cwaldbieser** [antoniandre/wave-ui#69]
If you have a strict Content Security Policy like:

    style-src: 'self'

The use of inline styles will be blocked by the policy.  Can this component in particular, and maybe others in general be configured to *not* use inline styles?

**Comment by antoniandre** [comment]
Hi @cwaldbieser, 
thanks for the suggestion, but this is not going to be in the scope for now. Too many components use inline styles to be very flexible, and it will not be possible to do otherwise unless I remove options for the user. Setting 10-15 common sizes is too many size when you need only one, and not the size you want for some users.
All the famous UI libraries have some inline styles, in order to offer more flexibility.
Hope that makes sense, thanks for the idea though. :)
